CREATE DATABASE IF NOT EXISTS authentication;
CREATE DATABASE IF NOT EXISTS messenger;
CREATE DATABASE IF NOT EXISTS files;
CREATE DATABASE IF NOT EXISTS frfl;
CREATE DATABASE IF NOT EXISTS post;
CREATE DATABASE IF NOT EXISTS rating;
CREATE DATABASE IF NOT EXISTS search_history;

GRANT ALL PRIVILEGES ON authentication.* TO 'user'@'%';
GRANT ALL PRIVILEGES ON messenger.* TO 'user'@'%';
GRANT ALL PRIVILEGES ON files.* TO 'user'@'%';
GRANT ALL PRIVILEGES ON frfl.* TO 'user'@'%';
GRANT ALL PRIVILEGES ON post.* TO 'user'@'%';
GRANT ALL PRIVILEGES ON rating.* TO 'user'@'%';
GRANT ALL PRIVILEGES ON search_history.* TO 'user'@'%';

FLUSH PRIVILEGES;